import type { Hotel } from '~/types'

export const HOTELS: Hotel[] = [
  {
    hotelId: '1',
    name: 'Hilton New York',
    cityCode: 'NYC',
    address: { cityName: 'New York' },
    rating: 4.6,
    amenities: ['WiFi', 'Pool', 'Gym', 'Spa'],
    price: { currency: 'USD', total: '349.00' },
  },
  {
    hotelId: '2',
    name: 'Marriott Marquis Times Square',
    cityCode: 'NYC',
    address: { cityName: 'New York' },
    rating: 4.5,
    amenities: ['WiFi', 'Pool', 'Gym'],
    price: { currency: 'USD', total: '379.00' },
  },
  {
    hotelId: '3',
    name: 'Hyatt Regency Miami',
    cityCode: 'MIA',
    address: { cityName: 'Miami' },
    rating: 4.4,
    amenities: ['WiFi', 'Pool', 'Beach'],
    price: { currency: 'USD', total: '289.00' },
  },
  {
    hotelId: '4',
    name: 'Hilton Chicago',
    cityCode: 'CHI',
    address: { cityName: 'Chicago' },
    rating: 4.5,
    amenities: ['WiFi', 'Pool', 'Gym'],
    price: { currency: 'USD', total: '259.00' },
  },
  {
    hotelId: '5',
    name: 'Marriott Los Angeles Downtown',
    cityCode: 'LAX',
    address: { cityName: 'Los Angeles' },
    rating: 4.3,
    amenities: ['WiFi', 'Pool', 'Gym'],
    price: { currency: 'USD', total: '269.00' },
  },
  {
    hotelId: '6',
    name: 'Hyatt Regency Denver',
    cityCode: 'DEN',
    address: { cityName: 'Denver' },
    rating: 4.4,
    amenities: ['WiFi', 'Pool', 'Spa'],
    price: { currency: 'USD', total: '229.00' },
  },
  {
    hotelId: '7',
    name: 'Hilton San Francisco Union Square',
    cityCode: 'SFO',
    address: { cityName: 'San Francisco' },
    rating: 4.5,
    amenities: ['WiFi', 'Gym'],
    price: { currency: 'USD', total: '319.00' },
  },
  {
    hotelId: '8',
    name: 'Marriott Marquis Washington DC',
    cityCode: 'WAS',
    address: { cityName: 'Washington' },
    rating: 4.4,
    amenities: ['WiFi', 'Pool', 'Gym'],
    price: { currency: 'USD', total: '299.00' },
  },
  {
    hotelId: '9',
    name: 'Hyatt Regency Orlando',
    cityCode: 'MCO',
    address: { cityName: 'Orlando' },
    rating: 4.6,
    amenities: ['WiFi', 'Pool', 'Spa'],
    price: { currency: 'USD', total: '249.00' },
  },
  {
    hotelId: '10',
    name: 'Hilton Boston Back Bay',
    cityCode: 'BOS',
    address: { cityName: 'Boston' },
    rating: 4.5,
    amenities: ['WiFi', 'Pool', 'Gym'],
    price: { currency: 'USD', total: '279.00' },
  },
]

